# Generated by Django 6.0 on 2026-09-22 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='normalized_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(db_index=True, default='camhr', max_length=50),
        ),
        migrations.CreateModel(
            name='RawJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='camhr', max_length=50)),
                ('job_id', models.CharField(db_index=True, max_length=50)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw_jobs',
                'ordering': ['-scraped_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'job_id'), name='uniq_raw_job_source_job_id')],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='raw_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_jobs', to='jobs.rawjob'),
        ),
    ]
