# Generated by Django 6.0 on 2026-09-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_normalized_at_job_source_rawjob_job_raw_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, unique=True)),
                ('vector', models.JSONField()),
                ('model_name', models.CharField(default='sentence-transformers/all-MiniLM-L6-v2', max_length=100)),
                ('dim', models.PositiveSmallIntegerField(default=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'skill_embeddings',
            },
        ),
    ]
